services:
  perfumegptaibackend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ${PWD}/host-config.mjs:/usr/src/app/host-config.mjs:ro
      - ${PWD}/public_key.pem:/usr/src/app/public_key.pem:ro
      - ${PWD}/.env:/usr/src/app/.env:ro

