services:
  perfumegptaibackend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - /home/vqn/project/perfume_gpt_ai_backend/mikro-orm.config.ts:/usr/src/app/mikro-orm.config.ts:ro
      - /home/vqn/project/perfume_gpt_ai_backend/public_key.pem:/usr/src/app/public_key.pem:ro
