services:
  perfumegptaibackend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /home/vqn/project/perfume_gpt_ai_backend/host-config.mjs:/usr/src/app/host-config.mjs:ro
      - /home/vqn/project/perfume_gpt_ai_backend/public_key.pem:/usr/src/app/public_key.pem:ro
      - /home/vqn/project/perfume_gpt_ai_backend/.env:/usr/src/app/.env:ro

