export const SLOW_STOCK_CONFIG = {
  FORECAST_RECENT_WEIGHT: 0.7,
  FORECAST_SHORT_TERM_WEIGHT: 0.3,
  MIN_FORECAST_DEMAND: 0.01,
  DAYS_OF_SUPPLY_THRESHOLD: 60,
  CANDIDATE_LIMIT: 30
} as const;

export const RESTOCK_CONFIG = {
  TREND_INCREASING_THRESHOLD: 1.15,
  TREND_DECLINING_THRESHOLD: 0.85
} as const;